- composer.json
- composer.lock
- vendor/composer/installed.json
- web/modules/contrib/easy_breadcrumb/LICENSE.txt
- web/modules/contrib/easy_breadcrumb/README.md
- web/modules/contrib/easy_breadcrumb/composer.json
- web/modules/contrib/easy_breadcrumb/config/install/easy_breadcrumb.settings.yml
- web/modules/contrib/easy_breadcrumb/config/schema/easy_breadcrumb.schema.yml
- web/modules/contrib/easy_breadcrumb/easy_breadcrumb.config_translation.yml
- web/modules/contrib/easy_breadcrumb/easy_breadcrumb.info.yml
- web/modules/contrib/easy_breadcrumb/easy_breadcrumb.install
- web/modules/contrib/easy_breadcrumb/easy_breadcrumb.links.menu.yml
- web/modules/contrib/easy_breadcrumb/easy_breadcrumb.links.task.yml
- web/modules/contrib/easy_breadcrumb/easy_breadcrumb.module
- web/modules/contrib/easy_breadcrumb/easy_breadcrumb.permissions.yml
- web/modules/contrib/easy_breadcrumb/easy_breadcrumb.routing.yml
- web/modules/contrib/easy_breadcrumb/easy_breadcrumb.services.yml
- web/modules/contrib/easy_breadcrumb/src/EasyBreadcrumbBuilder.php
- web/modules/contrib/easy_breadcrumb/src/EasyBreadcrumbConstants.php
- web/modules/contrib/easy_breadcrumb/src/Form/EasyBreadcrumbGeneralSettingsForm.php
- web/modules/contrib/easy_breadcrumb/tests/modules/easy_breadcrumb_test/easy_breadcrumb_test.info.yml
- web/modules/contrib/easy_breadcrumb/tests/modules/easy_breadcrumb_test/easy_breadcrumb_test.routing.yml
- web/modules/contrib/easy_breadcrumb/tests/modules/easy_breadcrumb_test/src/Controller/TestRouteController.php
- web/modules/contrib/easy_breadcrumb/tests/src/Kernel/EasyBreadcrumbBuilderTest.php
https://bytecubed.atlassian.net/browse/AWFM-26
> awf-26 - install easy_breadcrumb module

- config/core.extension.yml
- config/easy_breadcrumb.settings.yml
https://bytecubed.atlassian.net/browse/AWFM-26
> awfm-26 - additional config for easy_breadcrumb module

- config/webform.webform.apply_for_a_position_at_awf.yml
- config/webform.webform.get_involved.yml
- config/webform.webform.leadership_gift_form.yml
- config/webform.webform.main_donate_form.yml
- config/webform.webform.main_newsletter_signup.yml
https://bytecubed.atlassian.net/browse/AWFM-209
> awfm-209 - config to create webforms

- config/xmlsitemap.settings.node.article.yml
- config/xmlsitemap.settings.node.blog.yml
- config/xmlsitemap.settings.node.country.yml
- config/xmlsitemap.settings.node.donate_page.yml
- config/xmlsitemap.settings.node.news.yml
- config/xmlsitemap.settings.node.page.yml
- config/xmlsitemap.settings.node.resource.yml
- config/xmlsitemap.settings.node.safari.yml
- config/xmlsitemap.settings.node.staff.yml
https://bytecubed.atlassian.net/browse/AWFM-229
> awfm-229 - configuration for xmlsitemap

- config/core.entity_form_display.node.country.default.yml
- config/core.entity_form_display.node.donate_page.default.yml
- config/core.entity_form_display.node.resource.default.yml
- config/core.entity_form_display.node.safari.default.yml
- config/core.entity_form_display.node.staff.default.yml
- config/core.entity_view_display.node.country.default.yml
- config/core.entity_view_display.node.donate_page.teaser.yml
- config/core.entity_view_display.node.resource.default.yml
- config/core.entity_view_display.node.safari.default.yml
- config/core.entity_view_display.node.staff.teaser.yml
- config/field.field.node.country.body.yml
- config/field.field.node.country.field_field_featured.yml
- config/field.field.node.country.field_tags_animal.yml
- config/field.field.node.resource.field_tags_animal.yml
- config/field.field.node.safari.field_tags_animal.yml
- config/field.field.node.staff.field_heading.yml
https://bytecubed.atlassian.net/browse/AWFM-228
> awfm-228 - create Details field groups | Various - Content type clean up

- config/core.entity_form_display.node.hostory.default.yml
- config/core.entity_view_display.node.hostory.default.yml
- config/core.entity_view_display.node.hostory.teaser.yml
- config/custom_search.settings.results.yml
- config/field.field.node.hostory.body.yml
- config/language.content_settings.node.hostory.yml
- config/node.type.hostory.yml
https://bytecubed.atlassian.net/browse/AWFM-237
> awfm-237 - create History content type

- composer.lock
- vendor/composer/installed.json
- web/modules/contrib/honeypot/.travis.yml
- web/modules/contrib/honeypot/LICENSE.txt
- web/modules/contrib/honeypot/README.md
- web/modules/contrib/honeypot/composer.json
- web/modules/contrib/honeypot/config/install/honeypot.settings.yml
- web/modules/contrib/honeypot/config/optional/tour.tour.honeypot.yml
- web/modules/contrib/honeypot/config/schema/honeypot.schema.yml
- web/modules/contrib/honeypot/docker-compose.yml
- web/modules/contrib/honeypot/drupalci.yml
- web/modules/contrib/honeypot/honeypot.api.php
- web/modules/contrib/honeypot/honeypot.info.yml
- web/modules/contrib/honeypot/honeypot.install
- web/modules/contrib/honeypot/honeypot.links.menu.yml
- web/modules/contrib/honeypot/honeypot.module
- web/modules/contrib/honeypot/honeypot.permissions.yml
- web/modules/contrib/honeypot/honeypot.routing.yml
- web/modules/contrib/honeypot/src/Controller/HoneypotSettingsController.php
- web/modules/contrib/honeypot/tests/modules/honeypot_test/honeypot_test.info.yml
- web/modules/contrib/honeypot/tests/modules/honeypot_test/honeypot_test.routing.yml
- web/modules/contrib/honeypot/tests/modules/honeypot_test/src/Controller/HoneypotTestController.php
- web/modules/contrib/honeypot/tests/src/Functional/HoneypotAdminFormTest.php
- web/modules/contrib/honeypot/tests/src/Functional/HoneypotFormCacheTest.php
- web/modules/contrib/honeypot/tests/src/Functional/HoneypotFormProgrammaticSubmissionTest.php
- web/modules/contrib/honeypot/tests/src/Functional/HoneypotFormTest.php
@blakerscott This updates composer.lock to include antibot and honeypot contribs. Also has honeypot contrib module.
> AWFM-233 - composer.lock updated to include honeypot; contrib module added.

- config/block.block.awf_account_menu.yml
- config/block.block.awf_awfhomepageredesigncampaign.yml
- config/block.block.awf_awfhomepageredesignhero.yml
- config/block.block.awf_awfhomepageredesignmission.yml
- config/block.block.awf_branding.yml
- config/block.block.awf_breadcrumbs.yml
- config/block.block.awf_content.yml
- config/block.block.awf_help.yml
- config/block.block.awf_local_actions.yml
- config/block.block.awf_local_tasks.yml
- config/block.block.awf_main_menu.yml
- config/block.block.awf_page_title.yml
- config/block.block.awf_powered.yml
- config/block.block.awf_search.yml
- config/block.block.awf_tools.yml
- config/block.block.awf_views_block__homepage_multi_view_block_1.yml
- config/block.block.awf_webform_home_donate.yml
- config/block.block.awf_webform_newsletter.yml
- config/block.block.awfhomepageredesigncampaign_2.yml
- config/block.block.awfhomepageredesignhero_2.yml
- config/block.block.awfhomepageredesignmission_2.yml
- config/block.block.mainmenu.yml
- config/webform.webform.homepage_donate_form.yml
https://bytecubed.atlassian.net/browse/AWFM-231
> awfm-231: Committing blocks to config.

- config/core.entity_form_display.node.career.default.yml
- config/core.entity_view_display.node.career.default.yml
- config/core.entity_view_display.node.career.teaser.yml
- config/custom_search.settings.results.yml
- config/field.field.node.career.body.yml
- config/field.field.node.career.field_career_type.yml
- config/field.field.node.career.field_date.yml
- config/field.field.node.career.field_featured.yml
- config/field.field.node.career.field_featured_text.yml
- config/field.field.node.career.field_legacy_alias.yml
- config/field.field.node.career.field_legacy_id.yml
- config/field.field.node.career.field_legacy_revision_id.yml
- config/field.field.node.career.field_location.yml
- config/field.field.node.career.field_status.yml
- config/field.field.node.career.field_sub_heading.yml
- config/field.storage.node.field_career_type.yml
- config/field.storage.node.field_featured.yml
- config/language.content_settings.node.career.yml
- config/node.type.career.yml
https://bytecubed.atlassian.net/browse/AWFM-245
> awfm-245 - create Career content type

- config/core.entity_form_display.node.country.default.yml
- config/core.entity_form_display.node.safari.default.yml
- config/core.entity_form_display.node.staff.default.yml
- config/core.entity_view_display.node.staff.default.yml
- config/field.field.node.staff.field_legacy_revision_id.yml
https://bytecubed.atlassian.net/browse/AWFM-147
> awf-147 - updates to legacy fields

- config/core.entity_form_display.node.donate_page.default.yml
- config/core.entity_view_display.node.donate_page.default.yml
- config/field.field.node.donate_page.field_supporting_information.yml
- config/field.storage.node.field_supporting_information.yml
https://bytecubed.atlassian.net/browse/AWFM-166
> awf-166 - updates to Donate content type

- config/core.entity_form_display.node.country.default.yml
- config/core.entity_view_display.node.country.default.yml
- config/field.field.node.country.field_kml.yml
- config/field.field.node.country.field_weight.yml
- config/field.storage.node.field_featured.yml
- config/field.storage.node.field_kml.yml
- config/field.storage.node.field_weight.yml
- config/node.type.career.yml
- config/xmlsitemap.settings.node.country.yml
https://bytecubed.atlassian.net/browse/AWFM-129
https://bytecubed.atlassian.net/browse/AWFM-245
> Awf 245,129 - Content type updates

- web/sites/default/config/core.entity_form_display.node.history.default.yml
- web/sites/default/config/core.entity_view_display.node.history.default.yml
- web/sites/default/config/core.entity_view_display.node.history.teaser.yml
https://bytecubed.atlassian.net/browse/AWFM-237
> awfm-237 - updates to History content type

- web/sites/default/config/block.block.awf_webform_home_donate.yml
- web/sites/default/config/core.entity_view_display.node.donate_page.default.yml
https://bytecubed.atlassian.net/browse/AWFM-167
> awfm-167: Config for donate content type, donate bar.

- web/sites/default/config/block.block.prefacesocialsharing.yml
- web/sites/default/config/field.storage.node.field_all_tags.yml
- web/sites/default/config/views.view.blog.yml
review URL: http://awf-269-mp-awfd8-sandbox.pantheonsite.io/blog
> AWF-269: new blog landing page view and social sharing block placement update config

- web/sites/default/config/file_entity.type.document.yml
https://bytecubed.atlassian.net/browse/AWFM-341
> add kml and kmz filetypes to file_entity.type.document

- config/core.entity_view_display.node.landing_page.default.yml
- web/themes/custom/awf/templates/content/node--landing-page--full.html.twig
https://bytecubed.atlassian.net/browse/AWFM-168
> awfm-168: Landing Page

- config/core.entity_view_display.node.news.default.yml
https://bytecubed.atlassian.net/browse/AWFM-132
> awfm-132: Update news config.

- web/themes/custom/awf/templates/content/node--landing-page--full.html.twig
- web/themes/custom/awf/templates/field/field--field-sidebar-item-paragraph.html.twig
- web/themes/custom/awf/templates/paragraphs/paragraph.html.twig
https://bytecubed.atlassian.net/browse/AWFM-343
> awfm-343: Remove sidebar items label.

- config/views.view.hero_slideshow.yml
- config/views.view.history.yml
JIRA:  https://bytecubed.atlassian.net/browse/AWFM-312
> awfm-312; adding History views

- config/views.view.facts.yml
Also  Removing association from Random view mode
JIRA - https://bytecubed.atlassian.net/browse/AWFM-307
> awfm-307; updating Facts view to pull associated nods.

- config/views.view.pages.yml
https://bytecubed.atlassian.net/browse/AWFM-320
> awf-320 - config to create pages View

- config/views.view.reasons.yml
https://bytecubed.atlassian.net/browse/AWFM-323
> awf-323 - config to create Reasons view

- config/views.view.ways_to_give.yml
https://bytecubed.atlassian.net/browse/AWFM-334
> awf-334 - config to create Ways to Give view

- config/core.entity_view_display.paragraph.module.default.yml
- config/views.view.resources.yml
- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/gulpfile.js
- web/themes/custom/awf/src/sass/base/_base.scss
- web/themes/custom/awf/src/sass/base/_typography.scss
- web/themes/custom/awf/src/sass/styles/_layouts.scss
- web/themes/custom/awf/src/sass/styles/atoms/_caret.scss
- web/themes/custom/awf/src/sass/styles/components/_paragraph--type--module.scss
https://bytecubed.atlassian.net/browse/AWFM-272
> awfm-272: Resources

- config/context.context.species_content_type.yml
- config/views.view.blog.yml
- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles.scss
- web/themes/custom/awf/src/sass/styles/components/_view--blog.scss
- web/themes/custom/awf/templates/content/node--species--full.html.twig
https://bytecubed.atlassian.net/browse/AWFM-220
> awfm-220: species view

- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles.scss
- web/themes/custom/awf/src/sass/styles/components/_paragraph--type--history-list.scss
- web/themes/custom/awf/templates/field/field--paragraph--field-decade.html.twig
https://bytecubed.atlassian.net/browse/AWFM-276
> awfm-276: History

- web/themes/custom/awf/templates/content/node--species--full.html.twig
https://bytecubed.atlassian.net/browse/AWFM-220
> awf-220 - add map to Species template

- config/views.view.blog.yml
- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/base/_mixins.scss
- web/themes/custom/awf/src/sass/styles/components/_view--blog.scss
- web/themes/custom/awf/src/sass/styles/content_types/_species.scss
- web/themes/custom/awf/templates/content/node--species--full.html.twig
https://bytecubed.atlassian.net/browse/AWFM-220
> awfm-220: species mobile

- config/core.entity_view_display.block_content.call_to_action_block.default.yml
- config/image.style.full_cta.yml
- web/themes/custom/awf/awf.theme
- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/base/_extendables.scss
- web/themes/custom/awf/src/sass/styles.scss
- web/themes/custom/awf/src/sass/styles/components/_block--our-call.scss
- web/themes/custom/awf/src/sass/styles/components/_block--where-we-work.scss
- web/themes/custom/awf/src/sass/styles/components/_view--blog.scss
- web/themes/custom/awf/templates/field/field--block-content--field-link--call-to-action-block.html.twig
https://bytecubed.atlassian.net/browse/AWFM-220
> awfm-220: Our Call

- config/block.block.prefacesocialsharing.yml
- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles/components/_block--sidebar-basic-text.scss
https://bytecubed.atlassian.net/browse/AWFM-402
> awfm-402: social share

- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles/content_types/_blog.scss
https://bytecubed.atlassian.net/browse/AWFM-407
> awfm-407: Blog tweak

- config/core.entity_form_display.node.species.default.yml
- config/image.style.species_featured.yml
https://bytecubed.atlassian.net/browse/AWFM-401
> awfm-401: Config for focal point.

- config/views.view.reasons.yml
https://bytecubed.atlassian.net/browse/AWFM-418
> awf-418 - update Donate link on Reasons view

- config/context.context.country.yml
- web/themes/custom/awf/src/sass/components/wherewework.css
- web/themes/custom/awf/templates/block/block--views-block--country-map-block-1.html.twig
Review URL: http://awf-355-mp-awfd8-sandbox.pantheonsite.io/node/2936
> AWF-355: maps for country detail pages

- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/js/includes/wildlife-grid.js
- web/themes/custom/awf/src/sass/styles/components/_dlmenu.scss
https://bytecubed.atlassian.net/browse/AWFM-417
> awfm-417: nav changes

- config/views.view.blog.yml
- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles/content_types/_blog.scss
- web/themes/custom/awf/templates/content/node--blog--full.html.twig
https://bytecubed.atlassian.net/browse/AWFM-416
> awfm-416: author

- config/views.view.blog.yml
https://bytecubed.atlassian.net/browse/AWFM-424
> awfm-424: Update blog view.

- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles/content_types/_species.scss
https://bytecubed.atlassian.net/browse/AWFM-427
> awfm-427: species image

- config/editor.editor.basic_html.yml
- config/editor.editor.full_html.yml
- config/filter.format.basic_html.yml
- config/filter.format.full_html.yml
https://bytecubed.atlassian.net/browse/AWFM-400
> awf-400 - add Media Library option to WYSIWYGs

- config/filter.format.full_html.yml
- config/filter.format.plain_text.yml
- config/filter.format.restricted_html.yml
- config/user.role.anonymous.yml
- config/user.role.authenticated.yml
JIRA - https://bytecubed.atlassian.net/browse/AWFM-380
> awfm-380; updating configs for wysiwig

- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles/components/_paragraph--type--module.scss
- web/themes/custom/awf/src/sass/styles/components/_view--news.scss
- web/themes/custom/awf/src/sass/styles/content_types/_supplemental.scss
https://bytecubed.atlassian.net/browse/AWFM-438
> AWFM-438: Sidebar images

- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles/components/_view--species.scss
https://bytecubed.atlassian.net/browse/AWFM-435
> awfm-435: Species

- config/context.context.donate.yml
- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles.scss
- web/themes/custom/awf/src/sass/styles/content_types/_donate-page.scss
- web/themes/custom/awf/templates/content/node--donate-page--full.html.twig
https://bytecubed.atlassian.net/browse/AWFM-437
> awfm-437: Donate sidebar theming

- composer.json
- composer.lock
- config/core.extension.yml
- config/google_analytics.settings.yml
- config/responsive_image.styles.sidebar_image.yml
https://bytecubed.atlassian.net/browse/AWFM-445
> awfm-445: install modules 

- config/image.style.species_image.yml
- config/image.style.species_image_t_868x986_.yml
- config/image.style.vertical_image.yml
- config/image.style.vertical_image_405x472_.yml
- config/responsive_image.styles.horizontal_image.yml
- config/responsive_image.styles.sidebar_image.yml
- config/responsive_image.styles.species_image.yml
- config/responsive_image.styles.vertical_image.yml
- web/themes/custom/awf/awf.breakpoints.yml
https://bytecubed.atlassian.net/browse/AWFM-445
> awfm-445: Some responsive image styles for species.

- config/core.entity_form_display.node.species.default.yml
- config/core.entity_view_display.node.news.default.yml
- config/core.entity_view_display.node.species.default.yml
- config/core.entity_view_display.node.species.full.yml
- config/image.style.full_cta.yml
- config/image.style.full_cta_m_400x400_.yml
- config/image.style.full_cta_t_759x400_.yml
- config/image.style.hero_d_1440x440_.yml
- config/image.style.hero_m_485x380_.yml
- config/image.style.hero_t_745x380_.yml
- config/image.style.page_news_featured_image_d_656x_.yml
- config/image.style.page_news_featured_image_m_405x247_.yml
- config/image.style.species_hero_d_1440x750_.yml
- config/image.style.species_hero_m_400x750_.yml
- config/image.style.species_hero_t_760x750_.yml
- config/responsive_image.styles.blog_image.yml
- config/responsive_image.styles.hero.yml
- config/responsive_image.styles.news_image.yml
- config/responsive_image.styles.species_hero.yml
- config/views.view.hero.yml
- web/themes/custom/awf/awf.breakpoints.yml
https://bytecubed.atlassian.net/browse/AWFM-445
> awfm-445: Update config for responsive images (heros)

- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles/components/_block--homepage-articles.scss
https://bytecubed.atlassian.net/browse/AWFM-453
> AWFM-453: Homepage font weight.

- web/themes/custom/awf/dist/css/styles.css
- web/themes/custom/awf/src/sass/styles/components/_block--homepage-articles.scss
review URL http://awf-454-mp-awfd8-sandbox.pantheonsite.io/
> AWF-454: homepage multiview hover updates to match prod

- web/themes/custom/awf/templates/layout/html.html.twig
https://bytecubed.atlassian.net/browse/AWFM-454
> AWFM-454: Add Google Tag Manager.
